### PR TITLE
ahmadaccino's presentation

### PR DESCRIPTION
**Pull request by ahmad1702**
Thought i would set myself apart with a [lil presentation](https://docs.google.com/presentation/d/10qTrvAhfkgoVn4c8IchPzbp9U-flCfOC3CMNXv31SuM/edit?usp=sharing). my name will have the link to it:

Screenshot 2024-05-23 at 7 18 38 PM

### CODE REVIEW

**Review by igorbrigadir — APPROVED** [review]
LGTM!

**Review by alimagedayad — APPROVED** [review]
bro cooked

**Comment by coppinger** [comment]
hey u forgot this 👑

**Comment by premiare** [comment]
Hey Ahmad, thanks for letting my borrow your lambo the other week, that was really kind of you. And thanks for taking my grandma to her doctors appointment and buying her lunch and spending time with her, appreciate you homie!

**Comment by endingwithali** [comment]
conflicts. pls fix

**Comment by ahmad1702** [comment]
its ready to go....

**Comment by coppinger** [comment]
Verified, looks good, nice work @ahmad1702 🤝

**Comment by embedvr** [comment]
Hey Ahmad, thanks for letting me crash at your mansion and paying off my dog's student debt. He is a doctor now! Forever grateful.

**Pull request merged**
