### PR TITLE
Arnav Ghosh on his Way 👨‍💻

### PR DESCRIPTION
**Pull request by NotoriousArnav**
Would love be in the List, innit?

### CODE REVIEW

**Review by igorbrigadir — CHANGES_REQUESTED** [review]
Remove unnecessary extra file `NotoriousArnav.md`

**Review by endingwithali — CHANGES_REQUESTED** [review]
remove extra file.

**Comment by NotoriousArnav** [comment]
Why?? I wanna be Famous and make my momma proud 🥹🥹

**Comment by NotoriousArnav** [comment]
@endingwithali Extra file is removed, please merge

**Pull request merged**
