### PR TITLE
Save the drama for your llama and also me.

### PR DESCRIPTION
**Pull request by QuinnyPig**

### CODE REVIEW

**Comment by igorbrigadir** [comment]
LGTM!

**Review by igorbrigadir — APPROVED** [review]

**Comment by endingwithali** [comment]
what is an agony aunt?

**Comment by endingwithali** [comment]
whats the cost analysis here @QuinnyPig

**Comment by Warcop** [comment]
my bad @QuinnyPig i suggested we determine the impact before merge

**Review by Warcop — APPROVED** [review]

**Pull request merged**
